# Generated by Django 4.2 on 2023-04-23 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('name', models.CharField(max_length=50)),
                ('payment', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'client',
            },
        ),
    ]
