# Generated by Django 4.2 on 2023-04-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_user_isadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isAdmin',
        ),
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.CharField(default='user', max_length=50),
            preserve_default=False,
        ),
    ]
